// Resolve public-folder files so the site works on any host or sub-folder (vite base './').
export const asset = (path) => `${import.meta.env.BASE_URL}${String(path).replace(/^\/+/, '')}`

export const SITE = {
  name: 'ELIONEL',
  fullName: 'Elionel Vertus',
  major: 'Electrical Engineering',
  university: 'University of Central Florida',
  tagline: 'Embedded systems, firmware, and hardware',
  email: 'Elionel.Vertus@gmail.com',
  linkedin: 'https://www.linkedin.com/in/ElionelVertus',
  resume: asset('resume.pdf'),
  // Optional: put a photo in public/images/ and set it here, e.g. asset('images/elionel.jpg')
  photo: null,
  playlist: [
    {
      title: 'Menu Theme',
      artist: 'Smash Bros Melee',
      src: asset('music/Menu-Theme.mp3'),
      cover: asset('music-covers/Menu-Theme.png'),
    },
    {
      title: 'Redial',
      artist: 'Bomberman Hero',
      src: asset('music/Redial.mp3'),
      cover: asset('music-covers/Redial.jpg'),
    },
    {
      title: 'Comet Observatory',
      artist: 'Super Mario Galaxy',
      src: asset('music/Comet-Observatory.mp3'),
      cover: asset('music-covers/Comet-Observatory.ico'),
    },
    {
      title: 'Four-Limbed Titan',
      artist: 'Xenoblade Chronicles 2',
      src: asset('music/Four-Limbed-Titan.mp3'),
      cover: asset('music-covers/Xenoblade.webp'),
    },
    {
      title: 'Hotto',
      artist: 'Dragon Quest',
      src: asset('music/Hotto.mp3'),
      cover: asset('music-covers/Dragon-Quest.webp'),
    },
    {
      title: 'Venus Lighthouse',
      artist: 'Golden Sun',
      src: asset('music/Venus-Lighthouse.mp3'),
      cover: asset('music-covers/Golden-Sun.jpg'),
    },
  ],
}

// Home menu. `box` is [left, top, width, height] as a % of the 16:9 stage.
// `body` is [left, width] of the text block inside the panel, as a % of the panel.
export const HOME_ITEMS = [
  {
    id: 'experience',
    number: '01',
    title: 'EXPERIENCE',
    subtitle: 'Research • Firmware • Leadership',
    tone: 'red',
    icon: 'laptop',
    description: 'Undergraduate research, firmware leadership on Project SHRIKE, and team roles.',
    href: '#/experience',
    box: [0, 10, 49, 45],
    clip: 'polygon(0 0, 100% 0, 100% 100%, 0 100%)',
    body: [5, 64],
  },
  {
    id: 'about',
    number: '02',
    title: 'ABOUT ME',
    subtitle: 'Background • Skills • Interests',
    tone: 'blue',
    icon: 'person',
    description: 'Who I am, what I work with, and what I do outside of class.',
    href: '#/about',
    box: [49.6, 0, 41.7, 34],
    clip: 'polygon(0 0, 100% 0, 100% 100%, 0 100%)',
    body: [24, 66],
  },
  {
    id: 'resume',
    number: '03',
    title: 'RESUME',
    subtitle: 'Skills • Education • Experience',
    tone: 'pink',
    icon: 'doc',
    description: 'Open my current résumé (PDF) in a new tab.',
    href: 'resume',
    external: true,
    box: [55, 34.8, 36.3, 21.2],
    clip: 'polygon(0 0, 100% 0, 100% 100%, 0 100%)',
    body: [28.4, 68.6],
  },
  {
    id: 'projects',
    number: '04',
    title: 'PROJECTS',
    subtitle: 'Embedded • Circuits • Power',
    tone: 'green',
    icon: 'code',
    description: 'Firmware, sensing, analog, and power-systems work, including projects still in progress.',
    href: '#/projects',
    box: [0, 55.8, 42.5, 35.2],
    clip: 'polygon(0 0, 100% 0, 96% 100%, 0 100%)',
    body: [4, 62],
  },
  {
    id: 'linkedin',
    number: '05',
    title: 'LINKEDIN',
    subtitle: 'Connect • Network',
    tone: 'yellow',
    icon: 'linkedin',
    description: 'Open my LinkedIn profile in a new tab.',
    href: 'linkedin',
    external: true,
    box: [41.3, 56.6, 50, 34.4],
    clip: 'polygon(3.4% 0, 100% 0, 100% 47.4%, 80.4% 47.4%, 77.4% 100%, 0 100%)',
    body: [24, 52],
  },
  {
    id: 'contact',
    number: '',
    title: 'CONTACT',
    subtitle: '',
    tone: 'purple',
    icon: 'mail',
    description: 'Email me, or reach out on LinkedIn.',
    href: '#/contact',
    box: [80.6, 73.5, 10.7, 17.5],
    clip: 'polygon(14% 0, 100% 0, 100% 100%, 0 100%)',
    body: [24, 68],
  },
]

// Keyboard/gamepad-style movement between home panels.
export const HOME_NEIGHBORS = {
  experience: { right: 'about', down: 'projects', up: 'about', left: 'contact' },
  about: { left: 'experience', down: 'resume', right: 'resume', up: 'contact' },
  resume: { up: 'about', left: 'experience', down: 'linkedin', right: 'contact' },
  projects: { up: 'experience', right: 'linkedin', down: 'experience', left: 'contact' },
  linkedin: { left: 'projects', up: 'resume', right: 'contact', down: 'contact' },
  contact: { up: 'linkedin', left: 'linkedin', right: 'experience', down: 'experience' },
}

export const ABOUT = {
  role: 'STUDENT / BUILDER / GAMER',
  intro:
    "I'm an Electrical Engineering student at UCF focused on embedded systems, firmware, and the point where hardware meets software. I write STM32 firmware for sensor data acquisition in a research lab, co-lead firmware for Project SHRIKE, and enjoy work that spans analog circuits, power systems, and low-level code. Outside of engineering I'm into games, football, and the NBA.",
  quickFacts: [
    ['Degree', 'B.S. Electrical Engineering'],
    ['University', 'UCF — LEAD Scholars + EXCEL COMPASS'],
    ['Graduating', 'Expected Spring 2027'],
    ['Focus', 'Embedded systems, firmware, hardware bring-up'],
    ['Right now', 'Undergraduate researcher and SHRIKE firmware co-lead'],
    ['Languages', 'English and Haitian Creole (fluent)'],
  ],
  skills: [
    {
      label: 'Languages',
      tone: 'blue',
      items: ['C', 'C++', 'Python', 'ARMv7 Assembly', 'MATLAB', 'R', 'JavaScript'],
    },
    {
      label: 'Embedded & Hardware',
      tone: 'green',
      items: ['STM32', 'Raspberry Pi', 'Bare-metal programming', 'Microcontrollers', 'Digital circuits', 'Soldering', 'Breadboarding'],
    },
    {
      label: 'Tools & Lab',
      tone: 'yellow',
      items: ['Vivado', 'Multisim', 'PowerWorld', 'SolidWorks', 'Autodesk Inventor', 'Oscilloscope', 'Function generator', 'Digital multimeter'],
    },
  ],
  coursework:
    'Digital Systems, Digital Electronics, Electronics I & II, Linear Circuits, Engineering Statistics, Intro to Power Systems, Embedded Systems',
  interests: [
    ['game', 'Gaming'],
    ['code', 'Coding'],
    ['chip', 'Hardware'],
    ['gear', 'Robotics'],
    ['ball', 'Football & NBA'],
    ['image', 'Movies / Anime'],
    ['food', 'Good Food'],
    ['plane', 'Travel'],
  ],
  funFacts: [
    'First anime: Gurren Laggan',
    'Favorite movie: Rattatouie',
    'Favorite game series: Super Mario',
    'I listen to a lot of everything mainly RNB Rap and Hip-Hop',
    'LEAD a Super Smash Bros Team for 10 years since I was in middle school',
  ],
}

export const SIDE_QUESTS = [
  {
    title: 'LEAD Scholars Academy',
    category: 'Leadership / Events',
    icon: 'people',
    tone: 'pink',
    description:
      'Served as Leadership Week Events Director (2023–2024) and Lead Director (2024–2025), planning and running student events including tailgates and community activities.',
    tags: ['Events', 'Leadership', 'Budgeting'],
  },
  {
    title: 'SAE Baja UCF',
    category: 'Engineering Team',
    icon: 'gear',
    tone: 'blue',
    description:
      'Member of the SolidWorks team: chassis and subsystem modeling, plus MATLAB scripts for steering geometry and suspension behavior.',
    tags: ['SolidWorks', 'MATLAB', 'Design'],
  },
  {
    title: 'VEX Robotics',
    category: 'Competition',
    icon: 'trophy',
    tone: 'yellow',
    description:
      'VEX VRC results: 4× Tournament Champion, 2× Skills Champion, Design Award, 2× Excellence Award, Judges Award, and Tournament Finalist.',
    tags: ['Robotics', 'Competition', 'Awards'],
  },
  {
    title: 'IEEE & IEEE Computer Society',
    category: 'Student Organization',
    icon: 'chip',
    tone: 'green',
    description:
      'IEEE member since September 2022. Through IEEE Computer Society at UCF, I co-lead firmware for Project SHRIKE.',
    tags: ['IEEE', 'Firmware', 'Community'],
  },
]

export const PROJECT_FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'progress', label: 'In progress' },
  { id: 'embedded', label: 'Embedded' },
  { id: 'circuits', label: 'Circuits & Power' },
  { id: 'software', label: 'Software & Data' },
]

// Order matters: strongest electrical/embedded work first.
export const PROJECTS = [
  {
    id: 'shrike',
    title: 'Project SHRIKE',
    status: 'IN PROGRESS',
    tone: 'green',
    icon: 'chip',
    categories: ['embedded', 'progress'],
    period: 'Fall 2026 – Present',
    role: 'Firmware Co-Lead, IEEE Computer Society at UCF',
    summary:
      'Co-leading firmware for a custom Jetson-based portable workstation: Linux boot-up, board support package (BSP) configuration, and carrier-board bring-up.',
    tags: ['NVIDIA Jetson', 'Embedded Linux', 'BSP', 'PCB bring-up'],
    overview: [
      'Project SHRIKE is a multi-team IEEE Computer Society, IEEE, and HackUCF build: a self-contained portable workstation around an NVIDIA Jetson Orin module on a single custom carrier PCB, designed to mate with a Framework Laptop 13 chassis.',
      'I co-lead the firmware side. That means getting Linux to boot on the custom hardware, configuring the BSP for our carrier board, and working with the PCB team so power sequencing, GPIO, and peripheral communication line up between the schematic and the software.',
    ],
    highlights: [
      'Co-lead firmware development focused on Linux boot-up, BSP configuration, and carrier-board bring-up.',
      'Coordinate firmware and PCB integration for power sequencing, GPIO, peripheral communication, and hardware connectivity.',
      'Develop and debug the embedded Linux environment for device configuration, peripheral testing, and system-level hardware debugging.',
    ],
    architecture: {
      heading: 'Planned architecture (team spec, Rev 1.0)',
      items: [
        'One custom carrier PCB holds the compute module, power subsystem, embedded controller, display interface, networking, and storage.',
        'Firmware is planned in four layers: Orin BSP (pinmux and device tree), a fork of Framework’s open embedded-controller firmware, power-path configuration, and Linux userspace.',
        'A separate always-on ESP32 supervisor is planned to watch system health and force recovery if the main processor hangs.',
        'Bring-up is phased: prove the toolchain on a dev kit first, then reach a serial console on the custom board, then enable USB, storage, display, and PCIe one at a time.',
      ],
    },
    statusNote:
      'Work in progress. The team is in the design and bring-up planning stage, so there are no completed-build results to report yet.',
    stack: ['NVIDIA Jetson Orin', 'Embedded Linux', 'Device tree / BSP', 'UART console', 'Power sequencing', 'GPIO / I2C'],
  },
  {
    id: 'pose-estimation-research',
    title: 'Sensor Fusion & Neural Pose Estimation',
    status: 'RESEARCH',
    tone: 'blue',
    icon: 'radar',
    categories: ['embedded', 'progress'],
    period: 'Jan 2026 – Present',
    role: 'Undergraduate Researcher, University of Central Florida',
    summary:
      'STM32 firmware and Raspberry Pi data acquisition for real-time state estimation, supporting research on neural-process-based video object pose estimation.',
    tags: ['STM32', 'Raspberry Pi', 'Sensor fusion', 'Python'],
    overview: [
      'This is an ongoing undergraduate research project on neural process-based video object pose estimation. The experiments depend on clean, time-aligned data from several sensors at once.',
      'My part is the embedded side: firmware and hardware that collect data from IMU, encoder, LiDAR, and depth-camera sensors, and a Raspberry Pi that handles collection, preprocessing, and logging.',
    ],
    highlights: [
      'Develop STM32 firmware for embedded data acquisition, interfacing IMU, encoder, LiDAR, and depth-camera sensors used in real-time state-estimation experiments.',
      'Integrate the STM32 sensing hardware with a Raspberry Pi processing platform for sensor collection, preprocessing, logging, and multi-sensor data acquisition.',
      'Support evaluation of an Attentive Neural Process against a ConvLSTM baseline: 0.0016 test RMSE versus 0.0071, about 77.5% lower prediction error.',
    ],
    statusNote:
      'Ongoing research. The model comparison above comes from the lab’s evaluation, where I supported the work; my main contribution is the embedded sensing and data-acquisition side.',
    stack: ['STM32', 'C / C++', 'Raspberry Pi', 'Python', 'IMU / encoder / LiDAR / depth camera'],
  },
  {
    id: 'gridiron-gauntlet',
    title: 'Gridiron Gauntlet',
    status: 'IN PROGRESS',
    tone: 'red',
    icon: 'trophy',
    categories: ['progress'],
    period: 'In development',
    role: 'Details coming soon',
    summary: 'A project currently in development. The full write-up will be added here once it is ready to share.',
    tags: ['In development'],
    overview: [
      'Gridiron Gauntlet is still being built, so I am not listing scope, results, or features yet.',
      'Check back for a proper write-up, or email me if you would like to hear about it.',
    ],
    highlights: [],
    statusNote: 'Work in progress. No completed features or results are claimed here.',
    stack: [],
  },
  {
    id: 'armv7-energy',
    title: 'ARMv7 Assembly & Energy-Efficient Computing',
    status: 'COURSE PROJECT',
    tone: 'purple',
    icon: 'code',
    categories: ['embedded'],
    period: 'Spring 2026',
    role: 'Computer Organization (EEL 3801)',
    summary:
      'Bare-metal ARMv7 assembly that turns FASTQ quality characters into Phred scores, then optimized to cut estimated dynamic energy by about 5%.',
    tags: ['ARMv7 Assembly', 'Bare-metal', 'UART', 'Optimization'],
    overview: [
      'The program walks a DNA sequence and its FASTQ quality string, skips invalid bases, converts each ASCII quality value to a Phred score, and prints the total and average over UART.',
      'Part A used a branch-based loop. Part B restructured it with a fixed loop counter and conditional execution (MOVEQ / MOVNE) to remove branches, then compared the two versions with an instruction-count energy model.',
    ],
    highlights: [
      'Pointer-based memory traversal, register-level operations, conditional execution, and custom arithmetic (division by repeated subtraction) in ARMv7 assembly.',
      'UART output routines for printing strings, numbers, and characters from bare-metal code.',
      'Reduced estimated dynamic energy consumption by approximately 5% by restructuring loops and minimizing branch instructions, with identical program output.',
    ],
    statusNote: 'Completed course project. The 5% figure is an estimate from the course’s instruction-count energy model, not a hardware measurement.',
    stack: ['ARMv7 Assembly', 'UART', 'Instruction-count energy model'],
  },
  {
    id: 'fm-pll',
    title: 'FM Modulation & PLL Demodulation',
    status: 'LAB PROJECT',
    tone: 'yellow',
    icon: 'wave',
    categories: ['circuits'],
    period: 'Spring 2026',
    role: 'Lab project with a partner',
    summary:
      'Built and measured an FM modulator (XR2206 VCO) and a PLL demodulator (LM565) that recovers the original message signal.',
    tags: ['XR2206', 'LM565 PLL', 'TL084', 'Oscilloscope'],
    overview: [
      'We generated FM signals with an XR2206 voltage-controlled oscillator, characterized its voltage-to-frequency conversion, and then modulated it with sinusoidal and square-wave inputs.',
      'An LM565 phase-locked loop demodulated the FM signal back to the message, and we compared the recovered waveform against the original input.',
    ],
    highlights: [
      'Measured voltage-to-frequency conversion, peak frequency deviation, modulation index, and FM bandwidth, and checked them against theory.',
      'Observed the carrier component vanish at the zero-carrier condition of the modulated signal.',
      'Recovered the original signal through PLL demodulation; the recovered and input waveforms were very close in testing.',
    ],
    statusNote: 'Completed lab project.',
    stack: ['XR2206 VCO', 'LM565 PLL', 'TL084 op-amp', 'R&S RTM3004 oscilloscope', 'Tektronix AFG 3022B', 'Tektronix DMM4050'],
  },
  {
    id: 'amplifier-design',
    title: 'Transistor Amplifier Design',
    status: 'COURSE PROJECT',
    tone: 'pink',
    icon: 'bolt',
    categories: ['circuits'],
    period: 'Spring 2026',
    role: 'Electronics course project',
    summary:
      'Designed, simulated, built, and tested BJT amplifier circuits, comparing hand calculations, Multisim, and bench measurements.',
    tags: ['BJT', 'Multisim', 'Frequency response', 'Breadboard'],
    overview: [
      'Designed transistor-based amplifiers to meet specified performance requirements using transistor biasing, small-signal analysis, and frequency-response concepts.',
      'Each design was simulated in Multisim, prototyped on a breadboard, and measured on the bench.',
    ],
    highlights: [
      'Compared theoretical calculations, circuit simulations, and experimental measurements to evaluate gain, bandwidth, and overall performance.',
      'Validated BJT circuit behavior against Multisim results using an oscilloscope and function generator.',
    ],
    statusNote: 'Completed course project.',
    stack: ['BJT circuits', 'Multisim', 'Oscilloscope', 'Function generator', 'Breadboard'],
  },
  {
    id: 'wind-farm',
    title: 'Wind Farm Transmission System',
    status: 'COURSE PROJECT',
    tone: 'blue',
    icon: 'turbine',
    categories: ['circuits'],
    period: 'Fall 2025',
    role: 'Intro to Power Systems',
    summary:
      'Designed a transmission system for a 200 MW wind farm, using power-flow and N-1 contingency analysis in PowerWorld.',
    tags: ['PowerWorld', 'Power flow', 'N-1 contingency', 'Cost analysis'],
    overview: [
      'Scenario: connect a new 200 MW wind farm to the 69 kV level with at least two separate feeds, keep bus voltages between 0.95 and 1.10 per unit, and survive any single line or transformer outage.',
      'I analyzed about 50 transmission lines against 57 predefined N-1 contingencies, then added lines to remove overloads while weighing construction cost.',
    ],
    highlights: [
      'Eliminated transmission and transformer violations while keeping bus voltages within 0.95–1.10 p.u. and line loading within 100% of Limit A.',
      'Optimized four transmission-line additions totaling $8.759M.',
      'Evaluated an alternative configuration with approximately $1M lower capital cost.',
    ],
    statusNote: 'Completed course project with a written technical report.',
    stack: ['PowerWorld', 'Power flow', 'N-1 contingency analysis'],
  },
  {
    id: 'orange-race',
    title: 'Great Navel Orange Race Autonomous Vessel',
    status: 'TEAM PROJECT',
    tone: 'green',
    icon: 'boat',
    categories: ['embedded'],
    period: 'May – Aug 2024',
    role: 'Project Leader',
    summary:
      'Led a team building a lightweight vessel that steers itself along a race path using video-based distance tracking and Arduino servo control.',
    tags: ['Python', 'Arduino', 'Servo control', 'Computer vision'],
    overview: [
      'The vessel uses a real-time video-based distance-tracking system written in Python, which drives servo motors on an Arduino to steer along the race path.',
      'Area-based visual feedback updates the steering target continuously so the boat can respond to obstacles during testing.',
    ],
    highlights: [
      'Designed the video-based distance-tracking and steering-control system.',
      'Implemented visual feedback to update steering targets dynamically and support obstacle avoidance during testing.',
      'Led the team in building a lightweight hull from Styrofoam and basswood, balancing structural integrity against speed.',
    ],
    statusNote: 'Completed team project.',
    stack: ['Python', 'Arduino', 'Servo motors', 'Video tracking'],
  },
  {
    id: 'nba-analytics',
    title: 'NBA Predictive Analytics Platform',
    status: 'PERSONAL PROJECT',
    tone: 'red',
    icon: 'chart',
    categories: ['software'],
    period: 'Independent',
    role: 'Builder',
    summary:
      'A Python and Streamlit dashboard that forecasts NBA player stats and evaluates performance thresholds.',
    tags: ['Python', 'Pandas', 'Streamlit', 'Machine learning'],
    overview: [
      'A deployed predictive analytics platform that forecasts NBA player statistics and evaluates whether players clear performance thresholds.',
      'The prediction pipeline uses rolling averages, efficiency, minutes volatility, recent-game trends, and historical hit rates, served through an interactive Streamlit dashboard.',
    ],
    highlights: [
      'About 65% historical classification accuracy on threshold predictions.',
      'Serves 10+ monthly users through the Streamlit dashboard.',
    ],
    statusNote: 'Deployed. Figures are as listed on my résumé.',
    stack: ['Python', 'Pandas', 'Streamlit', 'Machine learning'],
  },
]

export const EXPERIENCES = [
  {
    id: 'undergraduate-researcher',
    title: 'Undergraduate Researcher',
    subtitle: 'Research',
    org: 'University of Central Florida',
    date: 'Jan 2026 – Present',
    icon: 'radar',
    tone: 'blue',
    bullets: [
      'Develop STM32 firmware for embedded data acquisition across IMU, encoder, LiDAR, and depth-camera sensors.',
      'Integrate STM32 sensing hardware with a Raspberry Pi for collection, preprocessing, and logging.',
      'Support evaluation of an Attentive Neural Process against a ConvLSTM baseline (0.0016 vs. 0.0071 test RMSE).',
    ],
    tags: ['STM32', 'Raspberry Pi', 'Sensor fusion', 'Python'],
    overview:
      'Embedded sensing and data acquisition for real-time state-estimation experiments in a research lab working on video-based object pose estimation.',
    project: 'pose-estimation-research',
  },
  {
    id: 'shrike-firmware',
    title: 'Firmware Co-Lead',
    subtitle: 'Project SHRIKE',
    org: 'IEEE Computer Society at UCF',
    date: 'Fall 2026 – Present',
    icon: 'chip',
    tone: 'green',
    bullets: [
      'Co-lead firmware for an embedded platform built on an NVIDIA Jetson Orin module: Linux boot-up, BSP configuration, and carrier-board bring-up.',
      'Coordinate firmware and PCB integration for power sequencing, GPIO, peripheral communication, and hardware connectivity.',
      'Develop and debug the embedded Linux environment for device configuration and peripheral testing.',
    ],
    tags: ['Embedded Linux', 'BSP', 'Jetson', 'Bring-up'],
    overview:
      'A multi-team hardware and software build. My focus is making the firmware and the custom carrier board work together.',
    project: 'shrike',
  },
  {
    id: 'baja-solidworks',
    title: 'SolidWorks Team Member',
    subtitle: 'SAE Baja UCF',
    org: 'SAE Baja UCF',
    date: '2023 – Present',
    icon: 'gear',
    tone: 'orange',
    bullets: [
      'Modeled chassis and subsystem components in SolidWorks, iterating on 3D prototypes to improve ergonomics and structural performance.',
      'Wrote MATLAB scripts to analyze steering geometry and suspension behavior and back design decisions with data.',
      'Worked with a multidisciplinary team to fold mechanical, electrical, and safety requirements into the vehicle design.',
    ],
    tags: ['SolidWorks', 'MATLAB', 'CAD', 'Teamwork'],
    overview: 'Mechanical design work on UCF’s SAE Baja off-road vehicle team.',
  },
  {
    id: 'lead-director',
    title: 'Lead Director',
    subtitle: 'LEAD Scholars Academy',
    org: 'LEAD Scholars Academy, UCF',
    date: '2024 – 2025',
    icon: 'people',
    tone: 'pink',
    bullets: [
      'Directed leadership initiatives and coordinated student teams, delegating responsibilities to keep projects on schedule.',
      'Planned and hosted student events, including tailgates and community activities.',
      'Partnered with students, staff, and organization leaders to resolve challenges and keep communication clear.',
    ],
    tags: ['Leadership', 'Events', 'Communication'],
    overview: 'A leadership role running student programming for the LEAD Scholars community.',
  },
  {
    id: 'leadership-week',
    title: 'Leadership Week Events Director',
    subtitle: 'LEAD Scholars Academy',
    org: 'LEAD Scholars Academy, UCF',
    date: '2023 – 2024',
    icon: 'rocket',
    tone: 'purple',
    bullets: [
      'Planned and coordinated Leadership Week events, overseeing logistics, scheduling, and execution.',
      'Developed and monitored event budgets, allocating resources within financial constraints.',
      'Collaborated with student leaders and organization teams to align activities and outcomes.',
    ],
    tags: ['Event planning', 'Budgeting', 'Coordination'],
    overview: 'Ran the logistics, schedule, and budget for a week of campus leadership events.',
  },
  {
    id: 'organizations-honors',
    title: 'Organizations & Honors',
    subtitle: 'IEEE • VEX • more',
    org: 'Student organizations and awards',
    date: '2022 – Present',
    icon: 'trophy',
    tone: 'yellow',
    bullets: [
      'IEEE member since September 2022; EXCEL member since November 2023.',
      'VEX VRC: 4× Tournament Champion, 2× Skills Champion, Design Award, 2× Excellence Award, Judges Award, Tournament Finalist.',
      'Named LEAD Scholar of the Month. Previously a member of the National Society of Black Engineers (Aug 2022 – May 2023).',
    ],
    tags: ['IEEE', 'VEX Robotics', 'Awards'],
    overview: 'Student organizations, competition results, and recognition.',
  },
  {
    id: 'dominos',
    title: 'Insider',
    subtitle: 'Domino’s',
    org: 'Domino’s, Orlando, FL',
    date: 'Jun – Aug 2025',
    icon: 'store',
    tone: 'teal',
    bullets: [
      'Handled multiple customer orders at once with accuracy under strict time limits.',
      'Operated and maintained equipment following safety and quality-control procedures.',
      'Coordinated with teammates on order prep and workflow during high-demand periods.',
    ],
    tags: ['Teamwork', 'Time management', 'Safety'],
    overview: 'A summer job in a fast-paced, high-volume environment.',
  },
]